sudo: required

language: ruby

services:
  - docker

script:
  - docker build -t avolpe/blog .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push USER/REPO;
    fi
