title: aVolpe Blog
description: Blog about Java EE and related technologies
author: Arturo Volpe
github: https://github.com/avolpe
about: I am a software enginner.
disqus_shortname: avolpeblog
google_analytics: UA-84291651-1
avatar_url: /static/img/avatar.jpg
encoding: utf-8

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/cochoVolpe"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/arturo-volpe-499a5263/"
    - icon: fa-stack-overflow
      link: "http://stackoverflow.com/users/1126380/arturo-volpe"
    - icon: fa-github
      link: "https://github.com/avolpe"
    - icon: fa-gitlab
      link: "https://gitlab.com/avolpe"

share:
  twitter_username: cochoVolpe
  fb_appid: 1263967477049232

urls:
    - text: About Me
      url: /about/
    - text: XML Feed
      url: /feed.xml

url: "https://www.volpe.com.py"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
