title: aVolpe Blog
description: Personal blog of Arturo Volpe.
author: Arturo Volpe
github: https://github.com/avolpe
about: I am a software engineer. Interested in open source, open data and devops.
disqus_shortname: avolpeblog
google_analytics: UA-84291651-1
avatar_url: /static/img/avatar.jpg
encoding: utf-8

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/cochoVolpe"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/arturo-volpe-499a5263/"
    - icon: fa-stack-overflow
      link: "https://stackoverflow.com/users/1126380/arturo-volpe"
    - icon: fa-github
      link: "https://github.com/avolpe"
    - icon: fa-gitlab
      link: "https://gitlab.com/avolpe"

share:
  twitter_username: cochoVolpe
  fb_appid: 1263967477049232

urls:
    - text: Home
      url: /
    - text: Resume
      url: /resume.html
    - text: Resume (Spanish)
      url: /cv
    - text: Projects
      url: /projects/
    - text: About Me
      url: /about/
    - text: XML Feed
      url: /feed.xml

url: "https://www.volpe.com.py"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - docker-compose.yml
  - Dockerfile
  - run.sh
  - LICENSE
  - README.md
  - nginx.conf