services:
  blog:
    build: .
    ports:
      - "80:80"
    container_name: avolpeblog
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=www.volpe.com.py,blog.volpe.com.py
      - LETSENCRYPT_HOST=www.volpe.com.py,blog.volpe.com.py
      - LETSENCRYPT_EMAIL=arturovolpe@gmail.com

  blog-devel:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "4000:4000"
    expose:
      - 4000
    volumes:
      - ./:/app/
